const CARDS = [
  {
    id: 1,
    background: 'default',
    border: 'default',
    position: 'default',
    text: null,
    cursorIcon: false,
    vertical: true,
    button: {
      variant: 'icon',
      text: 'This is a two line button that terminates with...',
      icon: true,
      background: 'default',
      border: 'default',
      disabled: false,
    },
  },
  {
    id: 2,
    variant: 'default',
    background: 'variant',
    border: 'default',
    position: 'default',
    text: null,
    cursorIcon: true,
    button: {
      variant: 'icon',
      text: 'This is a two line button that terminates with...',
      icon: true,
      background: 'variant',
      border: 'variant',
      disabled: false,
    },
  },
  {
    id: 3,
    variant: 'default',
    background: 'default',
    border: 'default',
    position: 'default',
    text: null,
    cursorIcon: false,
    button: {
      variant: 'default',
      text: 'This is a one line button',
      icon: false,
      background: 'default',
      border: 'default',
      disabled: false,
    },
  },
  {
    id: 4,
    variant: 'default',
    background: 'default',
    border: 'default',
    position: 'default',
    text: null,
    cursorIcon: false,
    button: {
      variant: 'icon',
      text: 'This is a two line button that terminates with...',
      icon: true,
      background: 'default',
      border: 'default',
      disabled: false,
    },
  },
  {
    id: 5,
    variant: 'border',
    background: 'default',
    border: 'default',
    position: 'variant',
    text: 'initial',
    cursorIcon: false,
    button: {
      variant: 'icon',
      text: 'This is a two line button that terminates with...',
      icon: true,
      background: 'default',
      border: 'default',
      disabled: false,
    },
  },
  {
    id: 6,
    variant: 'border',
    background: 'default',
    border: 'default',
    position: 'variant',
    text: 'disabled',
    cursorIcon: false,
    button: {
      variant: 'icon',
      text: 'This is a two line button that terminates with...',
      icon: true,
      background: 'default',
      border: 'default',
      disabled: true,
    },
  },
  {
    id: 7,
    variant: 'border',
    background: 'default',
    border: 'variant',
    position: 'variant',
    text: 'hover',
    cursorIcon: true,
    button: {
      variant: 'icon',
      text: 'This is a two line button that terminates with...',
      icon: true,
      background: 'variant',
      border: 'default',
      disabled: false,
    },
  },
]

export default CARDS
